const textData = {
  0: "",
  1: "<strong>Fecha de publicación:</strong> Marzo de 2024 </br>  <strong>Lugar:</strong> Estado Plurinacional de Bolivia</br> </br> <b>Institución responsable:</b> </br> Viceministerio de Educación Superior de Formación Profesional</br>Dirección General de Formación de Maestros</br>Unidad Especializada de Formación Continua – UNEFCO</br> </br> <b>Equipo de redacción y dirección:</b> </br>Fundación Ayuda en Acción </br> ProggettoMondo </br> Unidad Especializada de Formación Continua – UNEFCO </br> </br> <b>Créditos de las imágenes y flujogramas:</b> </br>Ilustraciones y dibujos: Fundación Ayuda en Acción; ProgettoMondo </br> Flujogramas: Fundación Ayuda en Acción </br>   </br> <b>Sitios oficiales:</b> </br> www.minedu.gob.bo </br> http://unefco.gob.bo/ </br> Bolivia, marzo, 2024 ",
  2: "texto a remplazarC",
  3: "<br> <br> <br>  El Plan de Formación para Maestras y Maestros es una modalidad de aprendizaje, compuesta por cursos cortos, desarrollada por el Ministerio de Educación a través de la Unidad Especializada de Formación Continua (UNEFCO) para profundizar y fortalecer habilidades y capacidades en la labor educativa, con un enfoque en la mejora de las prácticas y procesos formativos. Su propósito, de acuerdo con la Ley de Educación N° 070 “Avelino Siñani – Elizardo Pérez”, es trabajar por la universalización del Modelo Educativo Sociocomunitario Productivo, en atención a los diferentes niveles y áreas temáticas, con relevancia cultural y lingüística. <br> <br> Las prácticas restaurativas se han venido consolidando como una ciencia social emergente desde aproximadamente el 2013, época en la cual se estudian las acciones individuales y efectivas dirigidas hacia tres objetivos: el fortalecimiento comunitario, la resolución pacífica de conflictos y la  del daño o falta u ofensa cuando se produce. Se definen las mismas como respuestas no punitivas orientadas a la reparación del daño, potenciar las relaciones interpersonales, fortalecer la resolución de los conflictos y desarrollar soluciones que incluyan a todas las personas involucradas en un daño o falta u ofensa; tomando en cuenta que el manejo restaurativo de los afectos en el aula mejora la capacidad para el aprendizaje y la resiliencia. <br> <br> Los cuadernos del ciclo formativo: <b> “PRÁCTICAS RESTAURATIVAS PARA LA RESOLUCIÓN DE CONFLICTOS Y UNA VIDA LIBRE DE VIOLENCIA” </b>, nos invitan a replantearnos la manera en que enfrentamos los conflictos, desafiando los paradigmas arraigados de confrontación y castigo. A medida que nos sumergimos en las profundidades de las prácticas restaurativas, descubrimos su capacidad no solo para restaurar el daño o falta u ofensa causado por los conflictos, sino también para fortalecer nuestros lazos comunitarios y fomentar un clima de confianza y respeto mutuo. Este ciclo cuenta con tres cursos, en el Primer Curso, se aborda la parte normativa, lo que es y no es conflicto para luego introducir al enfoque restaurativo; en el Segundo Curso, se presenta; y en el Tercer Curso presentamos una caja de herramientas práctica para la aplicación en el quehacer educativo. <br> <br><b> COORDINACIÓN GENERAL - UNEFCO",
  4: " <br>  <br> <b>OBJETIVO HOLÍSTICO DEL CICLO</b> <br> Desarrollamos procesos de análisis y reflexión sobre los principios del enfoque restaurativo, en la incorporación de las prácticas restaurativas en la interacción educativa cotidiana, a través de las decisiones de promoción de una convivencia pacífica y libre de violencia educativa, para que maestras y maestros sean los principales actores en la resolución de conflictos.  <br><br> <b> OBJETIVO HOLÍSTICO DEL CURSO</b><br> Asumimos procesos restaurativos formales e informales en el entorno educativo, a través de prácticas restaurativas con herramientas y metodologías para la prevención y atención de conflictos, con participación de todos los miembros, para una comunidad educativa con cultura restaurativa. <br>",
  5: "",
  6: "En este espacio daremos inicio a la exploración de las herramientas restaurativas que fortalecerán la convivencia y la gestión positiva de los conflictos en la comunidad educativa. Esta actividad tiene como objetivo activar tus conocimientos previos, reflexionar sobre tus experiencias y abrir el diálogo sobre la importancia de contar con estrategias concretas para construir un ambiente de respeto, empatía y reparación.<br><br> Recuerda <b>descargar la plantilla</b> Actividad de Inicio tema 1 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  7: "",
  8: "Descubre cómo la escucha activa puede transformar tus relaciones y mejorar tu comunicación en este video práctico y accesible.<br><br> Recuerda <b>descargar la plantilla</b> Actividad de Extra tema 1 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  9: [
    "La escucha activa, ayuda a fortalecer las relaciones entre los miembros que conforman la comunidad educativa; al practicar la escucha activa en la comunicación, permite fomentar las interacciones y diálogo; por lo que, promoverá un ambiente inclusivo y de colaboración. . <br> La escucha activa se puede implementar de manera progresiva y constante en el entorno educativo. Es una herramienta poderosa para establecer y construir relaciones humanas sanas y positivas, por lo cual es importante su aplicación, porque permite: ",
    "<br>  <br> Ayuda a mejorar las relaciones entre maestras, maestros, estudiantes y otros integrantes de la unidad educativa. La práctica de la escucha activa fomenta la participación en el aula; y genera un ambiente inclusivo entre estudiantes, de manera que se sienten valorados y motivados para aprender ",
    "<br>  <br> Maestras y maestros pueden crear un entorno de aprendizaje estimulante mediante la escucha activa. Prestar verdadera atención a lo que dicen estudiantes, mostrar empatía y comprensión y estar dispuestos a escuchar sus preocupaciones y puntos de vista.",
    "  <br>  <br> En el contexto de las prácticas restaurativas, la escucha activa es esencial para facilitar el diálogo intergeneracional. Permite que todas las personas involucradas expresen sus opiniones, necesidades y sentimientos. Además, los conflictos se pueden resolver de manera constructiva y encontrar soluciones que satisfagan a todas las personas.",
  ],
  10: "",
  11: " Esta actividad te invita a reflexionar sobre tus propios hábitos de escucha en situaciones de comunicación cotidiana. A través de un breve cuestionario, podrás identificar cuáles son tus fortalezas y desafíos al momento de escuchar a otras personas.",
  12: "",
  13: "Para profundizar sobre <b> Declaraciones afectivas </b>, avanza con las flechas para revisar más información. ",
  14: "Te invitamos a explorar este artículo sobre la Comunicación No Violenta (CNV), un enfoque desarrollado por Marshall Rosenberg que promueve relaciones más empáticas, asertivas y humanas. <br><br>Para acceder al recurso y profundizar en el mismo, escanea el código QR que aparece junto a este texto desde tu celular o dispositivo móvil.",
  15: "Para profundizar sobre <b> Características principales de la declaración afectiva </b>, avanza con las flechas para revisar más información. ",
  16: "",
  17: "",
  18: "",
  19: "Para profundizar sobre <b> Ejemplos de declaraciones afectivas  </b>, avanza con las flechas para revisar más información. ",
  20: "",
  21: "",
  22: "En esta actividad, tendrás la oportunidad de aplicar de manera práctica las herramientas restaurativas que hemos venido explorando. <br> <br> Trabajaremos a partir de casos, situaciones o propuestas que permitirán fortalecer habilidades de comunicación, escucha activa, declaración afectiva y resolución colaborativa de conflictos.<br><br> Recuerda <b>descargar la plantilla</b> Actividad de Sugerida tema 1 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  23: "",
  24: "Esta actividad tiene como propósito activar la reflexión inicial sobre el uso de herramientas restaurativas en el entorno educativo. A través de este ejercicio, podrás identificar cuáles son tus conocimientos, percepciones y expectativas respecto a la gestión de conflictos y la construcción de relaciones empáticas.<br><br> Recuerda <b>descargar la plantilla</b> Actividad de Inicio tema 2 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  25: "Para profundizar sobre <b> Círculos restaurativos escolares </b>, avanza con las flechas para revisar más información. ",
  26: "",
  27: "",
  28: "Esta actividad propone la implementación de un círculo restaurativo para abordar situaciones de violencia verbal y física entre estudiantes, fortaleciendo el sentido de comunidad y promoviendo una comunicación respetuosa. A través de dinámicas, reflexiones guiadas y acuerdos colectivos, trabajaremos en sensibilizar a las y los estudiantes sobre su rol en la mejora de la convivencia escolar.<br><br> Recuerda <b>descargar la plantilla</b> Actividad de Inicio extra tema 2 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  29: "Te invitamos a visualizar el siguiente video, que aborda de forma clara y práctica el rol del facilitador/a en procesos restaurativos. Este material complementario te permitirá reflexionar sobre las habilidades clave, los desafíos comunes y las recomendaciones para conducir espacios restaurativos con enfoque participativo, empático y respetuoso.<br><br>Para acceder al recurso y profundizar en el mismo, escanea el código QR que aparece junto a este texto desde tu celular o dispositivo móvil.",
  30: "",
  31: "",
  32: "<b>Recibir el objeto/artículo para hablar</b> es una <b>invitación para compartir</b> con el grupo. El artículo ayuda a asegurar que cada integrante del círculo tenga la <b>oportunidad de colaborar</b> a su propio ritmo y manera <b>sin ser interrumpido</b> mientras habla. Cada participante comparte lo que quiere o permanece en silencio durante su turno, <b>pasando el objeto</b> a la persona que está a su lado, hasta realizar el <b>cierre del círculo</b>. <br><br>El <b>objeto de diálogo</b> también actúa como <b>sensibilizador cultural</b>, adquiriendo un <b>significado especial</b> según el grupo. La persona facilitadora y los participantes pueden <b>escoger un objeto simbólico</b> relacionado con el tema o la identidad del grupo. Por ejemplo: <br><br>*  Un <b>espejo de plástico</b> para reflexionar sobre habilidades personales. <br><br>*  Una <b>pelota de goma</b> o <b>muñeca de esponja</b> en temas sensibles como el <b>acoso escolar</b>, para aliviar tensión.(ProgettoMondo, 2018) <br><br>",
  33: "Para profundizar sobre <b> Tipos de círculos restaurativos escolares  </b>, avanza con las flechas para revisar más información. ",
  34: "texto a remplazarM",
  35: "Las <b>medidas reactivas</b> son aquellas que se activan después de ocurrido un problema. Su objetivo es <b>esclarecer la situación</b> identificando: <br><br> a. <b>Quiénes</b> están involucrados. <br>b. <b>Cómo afecta el problema</b> a estudiantes, maestras/os y familias. <br>c. <b>Reflexión conjunta</b> para evitar su repetición. <br><br>Los <b>círculos restaurativos reactivos</b> se aplican en conflictos que involucran a <b>varios estudiantes</b>. Ejemplos incluyen: <br><br> *  <b>Acuerdos para no cumplir tareas</b>.<br> *  <b>Pérdida recurrente de materiales</b>.<br>*  <b>Camarillas</b> o <b>enfrentamientos grupales</b>.<br>*  <b>Competencia desleal</b>, generando un <b>ambiente de malestar</b>. <br><br><br>Es clave aclarar que estos círculos <b>no buscan culpables</b>, sino soluciones. Su <b>éxito aumenta</b> cuando se usan de forma <b>preventiva y cotidiana</b>, facilitando la <b>apropiación colectiva</b> de métodos restaurativos. ",
  36: "Para profundizar sobre <b> Proceso para generar círculos restaurativos escolares  </b>, avanza con las flechas para revisar más información. ",
  37: "",
  38: "",
  39: "Para profundizar sobre <b> ¿Cuándo aplicar los círculos restaurativos en la comunidad educativa?  </b>, avanza con las flechas para revisar más información. ",
  40: "",
  41: "En este video, Jean Schmitz, experto en prácticas restaurativas, comparte de forma clara y accesible cómo implementar círculos restaurativos en contextos escolares. A través de ejemplos y explicaciones prácticas, el video ayuda a comprender los elementos clave para facilitar estos espacios con enfoque en la participación, la reparación del daño y la mejora de la convivencia.<br><br>Para acceder al recurso y profundizar en el mismo, escanea el código QR que aparece junto a este texto desde tu celular o dispositivo móvil.",
  42: "Para profundizar sobre <b> momentos para la realización de los círculos restaurativos en la comunidad educativa  </b>, avanza con las flechas para revisar más información. ",
  43: "Esta actividad nos invita a profundizar en el uso de las herramientas restaurativas como estrategias cotidianas de convivencia.<br> <br> A través de ejercicios prácticos, reflexivos o de simulación, exploraremos cómo aplicar técnicas como la escucha activa, las declaraciones afectivas y los círculos restaurativos para transformar los conflictos en oportunidades de diálogo y crecimiento. <br><br> Recuerda <b>descargar la plantilla</b> Actividad de Sugerida tema 2 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  44: "",
  45: "El propósito de este espacio es reflexionar de manera inicial sobre las prácticas restaurativas y las herramientas que fortalecen la convivencia en el aula y en la comunidad educativa. A través de esta actividad, te invitamos a explorar tus ideas y experiencias previas, abriendo el camino para aplicar estrategias que promuevan el respeto, el diálogo y la reparación en el entorno escolar. <br><br> Recuerda <b>descargar la plantilla</b> Actividad de Inicio tema 3 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  46: "",
  47: "Para profundizar sobre <b> los momentos para realizar reuniones restaurativas </b>, avanza con las flechas para revisar más información. ",
  48: "La realización de una <b>reunión restaurativa</b> en el ámbito educativo requiere un <b>ambiente de respeto</b>, <b>apertura</b> y <b>disposición al diálogo</b> por parte de todos los involucrados. Es fundamental que exista una <b>preparación previa</b> para comprender el proceso y sus objetivos, y que la <b>persona facilitadora</b> guíe la sesión con <b>imparcialidad</b>, enfocándose en la <b>reparación del daño</b> y la <b>restauración de relaciones</b>. Además, tanto la <b>víctima</b> como la <b>persona que ofendió</b> y sus <b>apoyadores</b> deben participar de manera <b>voluntaria</b>. <br><br>Otras condiciones esenciales son que la <b>persona ofensora reconozca su responsabilidad</b>, que la reunión esté <b>cuidadosamente preparada</b>, y que por cada incidente se lleve a cabo una <b>única reunión</b>. Incluso cuando existen <b>diferentes versiones de los hechos</b> o <b>niveles de responsabilidad</b>, el facilitador debe trabajar para construir un <b>entendimiento mutuo</b> antes del encuentro, garantizando así que el <b>proceso restaurativo</b> sea efectivo y genere un <b>impacto positivo</b> en la <b>convivencia escolar</b>. ",
  49: "",
  50: "Para profundizar sobre <b> Proceso para realizar una reunión restaurativa  </b>, avanza con las flechas para revisar más información. ",
  51: "",
  52: "Para profundizar sobre <b>  Elementos de la preparación de reuniones restaurativas  </b>, avanza con las flechas para revisar más información. ",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "Para profundizar sobre <b> Con relación a la persona que ofende  </b>, avanza con las flechas para revisar más información. ",
  58: "",
  59: [
    " La escucha activa, la empatía y la comunicación asertiva fortalecen los vínculos entre los participantes y permiten abordar los conflictos de manera constructiva.",
    "Estas competencias permiten conducir procesos restaurativos de manera justa, eficiente y adaptada al contexto educativo.",
  ],
  60: "",
  61: "En esta actividad analizaremos un caso real para aplicar el enfoque restaurativo ante situaciones de violencia escolar.<br> A través de la historia de Sandra, reflexionaremos sobre los tipos de violencia presentes, las respuestas preventivas que pudieron haberse implementado, y construiremos una ruta de abordaje restaurativa que fortalezca la protección y el bienestar en la comunidad educativa. <br><br> Recuerda <b>descargar la plantilla</b> Actividad de Sugerida tema 3 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  62: "<br> <b>Alternativa</b>: Indica que las <b>prácticas restaurativas</b> ofrecen una <b>variedad de opciones</b> para enfrentar conflictos y daños. <br><br> <b>Autonomía</b>: Permite a las partes involucradas en la práctica restaurativa la <b>libertad de decir si participar o no</b>, y <b>cómo desean que se lleven a cabo</b> las prácticas. <br><br> <b>Círculo restaurativo</b>: Un <b>método de intervenir en grupo</b> donde se discute y decide conjuntamente cómo <b>reparar un problema o conflicto</b>. <br><br> <b>Daño</b>: Define la afectación o dolor <b>físico</b>, <b>psicológico</b>, <b>material</b>, <b>económico</b> o <b>moral</b> que puede ser ocasionado por un crimen. <br><br> <b>Diálogo</b>: Es <b>central en las prácticas restaurativas</b> para facilitar la <b>comprensión</b> y la generación de <b>soluciones creativas</b>. <br><br> <b>Objeto del diálogo</b>: Es el elemento que permite <b>dinamizar los círculos restaurativos</b> y prácticas restaurativas. <br><br> <b>Restaurativa</b>: Son métodos que buscan <b>construir y fortalecer la comunidad escolar</b>, <b>prevenir</b> y <b>gestionar conflictos</b>, y resolverlos de manera positiva. Se enfocan en la <b>reparación del daño</b> y la <b>restauración de relaciones</b>, en lugar de la imposición de castigos. <br><br> <b>Personas de apoyo en el círculo restaurativo</b>: Se dividen en:a) <b>Apoyo al estudiante ofensor/a</b>;b) <b>Apoyo al estudiante víctima</b>;c) <b>Otras que pueden estar en el primero o segundo caso</b>;cuyo rol es participar en reuniones o círculos restaurativos. La intención no es <b>revictimizar</b>, sino mostrar que están ahí como un <b>entorno protector</b> y <b>promotor de cumplimiento de compromisos</b>. <br><br> <b>Relaciones</b>: Se enfocan en mejorar las <b>relaciones personales o sociales</b> afectadas por un crimen. <br><br> <b>Reparación</b>: Intenta ajustar o compensar los daños <b>físicos</b> o <b>morales</b> a través de medios <b>simbólicos</b> o <b>concretos</b>. <br><br>",
  63: "<br><b>Acebedo, F. y. (2009)</b>. Manual para facilitación de círuclos de diálogo en instituciones educativas. Costa Rica. <br><br><b>APPF.es Formación online de calidad. (Octubre de 2018)</b>. Obtenido de APPF.es Formación online de calidad: https://www.appf.edu.es/consejos-para-potenciar-la-escucha-activa-entre-los-alumnos/ <br><br><b>Bisquerra, R. (2011)</b>. Educación emocional: Propuestas para educadores y familia. Bilbao, España: Desclée de Brouwer, S.A. <br><br><b>Bolivariano, I. E. (2023)</b>. Institución Educativa Bolivariano. <br><br><b>CampusFADJventud. (Abril de 2019)</b>. www.campusfad.org. Obtenido de www.campusfad.org: https://www.campusfad.org/blog/crear-comunidad-desde-las-practicas-restaurativas/ <br><br><b>Ciencia Latina Revista Multidisciplinar. (Octubre de 2022)</b>. www.semanticscholar.org. Obtenido de www.semanticscholar.org: https://pdfs.semanticscholar.org/20f3/f66d77ccd9eb0ca0f5d615fca6d646363742.pdf <br><br><b>Diariodemediacion. (2018)</b>. www.diariodemediacion.es. Obtenido de www.diariodemediacion.es: https://www.diariodemediacion.es/reuniones-restaurativas-caso-rea-practicas-restaurativas/ <br><br><b>Educación 3.0.com. (s.f.)</b>. Obtenido de Educación 3.0.com: https://www.educaciontrespuntocero.com/recursos/educacion-emocional/escucha-activa-respeto-empatia-concentracion-aula/ <br><br>",
  64: "<br><b>Educalidad. (Mayo de 2021)</b>. www.educalidad.com. Obtenido de www.educalidad.com: https://educalidad.com/la-importancia-de-las-practicas-restaurativas-2 <br><br><b>Escuela y pedagogía. (Enero de 2021)</b>. www.educacionbogota.edu. Obtenido de www.educacionbogota.edu: https://escuelaypedagogia.educacionbogota.edu.co/miradas/cuando-el-arbol-de-la-justicia-restaurativa-tapa-el-bosque-de-las-practicas-restaurativas <br><br><b>Escuelas sin racismo. (Noviembre de 2020)</b>. www.escuelasinracismo.org. Obtenido de www.escuelasinracismo.org: https://www.escuelasinracismo.org/ficheros/documentos/Guia_definitiva_(_Logo_MISSM)(1).pdf <br><br><b>Hopkins, B. (2020)</b>. Prácticas restaurativas en el aula. Palma, España: GOIB. <br><br><b>https://pazatuidea.org. (Mayo de 2022)</b>. Practica restaurativa en instituciones educativas: una guia para construir relaciones de cuidado. Obtenido de https://pazatuidea.org/wordpress/wp-content/uploads/2022/05/Practicas_restaurativas_en_instituciones.pdf <br><br><b>inemes.es. (Abril de 2023)</b>. Obtenido de inemes.es: https://www.inesem.es/revistadigital/educacion-sociedad/circulos-restaurativos/ <br><br><b>-INSA, I. S. (2019)</b>. www.transparencia.gob.sv. Obtenido de www.transparencia.gob.sv: https://www.transparencia.gob.sv/institutions/isna/documents/352832/download <br><br><b>Instituto Salvadoreño para el Desarrollo Integral de la niñez y la adolescencia. (2019)</b>. www.transparencia.gob. Obtenido de www.transparencia.gob.: https://www.transparencia.gob.sv/institutions/isna/documents/352832/download <br><br>",
  65: "<b>Jean Schmitz. (2020)</b>. Diario de Mediación. Obtenido de https://www.bing.com/videos/ riverview/o?pglt=43&q=jean+Smith+y+ circulos+restaurativos& cvid=3403b305a61f4092a76d1dc4ddc5d8d0&gs_= EgZjaHJvbWUyBggAEEUYOTIGCAEQABhAMggIAhDpBxj8VdIBCDkzMTVqMGoxqAIAs AIB&PC=U531&ru=%2fsearch%3fpglt%3d43%26q%3djean <br><br><b>Martin, J. G. (2020)</b>. Gesalt Salut. Obtenido de Comunicación No Violenta de Rosenberg: 4 pasos: https://gestaltsalut.com/comunicacion-noviolenta-rosenberg/ <br><br><b>Mediación escolar. (2018)</b>. www.mediacionescolar.org. Obtenido de www.mediacionescolar.org: https://mediacionescolar.org/circulos-de-dialogo-mediacion-escolar/ <br><br><b>mediemos.com. (2019)</b>. Obtenido de Mediemos.com: https://mediemos.pro/mediacion/declaraciones-afectivas-en-la-escuela/ <br><br><b>Ministerio de Educación.gob.bo. (2022)</b>. Procedimientos para la detección, actuación y derivación de situaciones de violencia en la unidad educativa UNEFCO. Tarija. <br><br><b>Pazatuidea.org. (2022)</b>. Obtenido de www.pazatuidea,org: https://pazatuidea.org/wordpress/wp-content/uploads/2022/05/Practicas_restaurativas_en_instituciones.pdf <br><br><b>Prácticas restaurativas en el ámbito educativo. (2024)</b>. Obtenido de https://educacion.gob.ec/practicas-restaurativas-en-el-ambito-educativo/ <br><br>",
  66: "<b>ProgettoMondo, Educo, Fundación La Paz (2018)</b>. Práctidas restuarativas para la prevención y gestion de conflictos en el ámbito educativo. La Paz: Imprenta Cerro Azul SRL. <br><br><b>Rodríguez, R. (2005)</b>. La acción tutorial para favorecer la convivencia: la disciplina. <br><br><b>San Martín, J. A. (2003)</b>. La mediación escolar. Un camino para la gestión del conflicto escolar. Madrid, España. <br><br><b>Schmitz, J. (2020)</b>. Manual de prácticas restaurativas en el ámbito educativo. Ecuador. <br><br><b>schooltivity.com. (s.f.)</b>. Obtenido de schoolyivity.com: https://schooltivity.com/blog/las-ventajas-de-la-escucha-activa-en-el-aula <br><br><b>Terres des hommes. (2018)</b>. Prevención de la violencia escolar y la convivencia pacífica. Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas. Perú: Pixel Gráfico Impresores S.A.C. <br><br><b>www.inspire-edu. (2018)</b>. Escucha activa en entornos educativos. Obtenido de Escucha activa en entornos educativos: https://inspire-edu.tech/escucha-activa-en-entornos-educativos/ <br><br>",
  67: "Este anexo ofrece una guía práctica y detallada para la facilitación de reuniones restaurativas en el contexto educativo. Su propósito es orientar paso a paso a las maestras, maestros o personal facilitador en la conducción de estos espacios, asegurando un proceso respetuoso, participativo y orientado a la reparación del daño. A través de este guion, se promueve una cultura de diálogo, responsabilidad y construcción colectiva de soluciones. <br><br> Recuerda <b>descargar la plantilla</b> ANEXO o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
};
const titlesData = {
  0: "",
  1: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
  2: "CONTENIDO",
  3: "PRESENTACIÓN",
  4: "DATOS GENERALES DEL CURSO",
  5: "",
  6: "Ejercicio de escucha activa",
  7: "Escucha activa",
  8: "Técnica de escucha activa",
  9: "Importancia de la escucha activa",
  10: "Sugerencias para una escucha activa",
  11: "Test sobre escucha activa",
  12: "Beneficios de la escucha activa",
  13: "Declaraciones afectivas",
  14: "Comunicación no violenta",
  15: "Características principales de la declaración afectiva",
  16: "Modo acusador Vs Modo Declaración afectiva",
  17: "Dinámica Construyendo declaraciones afectivas",
  18: "Construcción de las declaraciones afectivas",
  19: "Ejemplos de declaraciones afectivas",
  20: "Comprobación de las declaraciones afectivas",
  21: "Beneficios de las declaraciones afectivas",
  22: "Construyendo guías de escucha activa",
  23: "",
  24: "Analizando una historia",
  25: "Círculos restaurativos escolares",
  26: "Aplicación de los círculos restaurativos escolares",
  27: "Momentos del círculo restaurativo",
  28: "Ficha de círculo restaurativo",
  29: "Desarrollo de un círculo restaurativo",
  30: "Objetivos que se alcanzan  con un círculo restaurativo",
  31: "El objeto del diálogo",
  32: "El objeto del diálogo como algo representativo",
  33: "Tipos de círculos restaurativos escolares",
  34: "Ejemplos de círculos proactivos y preventivos",
  35: "Círculos restaurativos reactivos",
  36: "Proceso para generar círculos restaurativos escolares",
  37: "Rol del facilitador en círculos restaurativos",
  38: "Problemas que se pueden abordar desde los círculos restaurativos",
  39: "¿Cuándo aplicar los círculos restaurativos en la comunidad educativa?",
  40: "Momentos para la realización de los círculos restaurativos en la comunidad educativa",
  41: "Círculos restaurativos en centros educativos",
  42: "Momentos para la realización de los círculos restaurativos en la comunidad educativa",
  43: "Preparar un círculo restaurativo",
  44: "",
  45: "Accionar ante un conflicto",
  46: "Concepto de reunión restaurativa",
  47: "Los momentos para realizar reuniones restaurativas",
  48: "Condiciones para realizar una reunión restaurativa",
  49: "Previo a la reunión restaurativa",
  50: "Proceso para realizar una reunión restaurativa",
  51: "Persona que facilita la reunión",
  52: "Elementos de la preparación de reuniones restaurativas",
  53: "Desarrollo de la reunión",
  54: "Seguimiento",
  55: "Derechos, necesidades y oportunidades",
  56: "Derechos de la víctima Vs Necesidades de la víctima",
  57: "Con relación a la persona que ofende",
  58: "Rol del facilitador de las reuniones restaurativas",
  59: [
    "Habilidades de escucha activa y comunicación empática",
    " Habilidades para la gestión restaurativa de conflictos",
  ],
  60: "Reunión Familiar",
  61: "Resolución de conflicto en aula",
  62: "Glosario",
  63: "Bibliografía",
  64: "Bibliografía",
  65: "Bibliografía",
  66: "Bibliografía",
  67: "Anexo: Guión  para la persona que facilita la reunión restaurativa",
};

const layoutData = {
  0: "Alayout",
  1: "Blayout",
  2: "Clayout",
  3: "Blayout",
  4: "Dlayout",
  5: "Elayout",
  6: "Flayout",
  7: "Olayout",
  8: "Ilayout",
  9: "Mlayout",
  10: "Olayout",
  11: "Flayout",
  12: "Olayout",
  13: "Jlayout",
  14: "Ilayout",
  15: "Jlayout",
  16: "Playout",
  17: "Olayout",
  18: "Olayout",
  19: "Jlayout",
  20: "Olayout",
  21: "Playout",
  22: "Flayout",
  23: "Elayout",
  24: "Flayout",
  25: "Jlayout",
  26: "Olayout",
  27: "Olayout",
  28: "Flayout",
  29: "Ilayout",
  30: "Olayout",
  31: "Olayout",
  32: "Dlayout",
  33: "Jlayout",
  34: "Olayout",
  35: "Dlayout",
  36: "Jlayout",
  37: "Olayout",
  38: "Playout",
  39: "Jlayout",
  40: "Olayout",
  41: "Ilayout",
  42: "Jlayout",
  43: "Flayout",
  44: "Elayout",
  45: "Flayout",
  46: "Olayout",
  47: "Jlayout",
  48: "Dlayout",
  49: "Olayout",
  50: "Jlayout",
  51: "Olayout",
  52: "Jlayout",
  53: "Playout",
  54: "Olayout",
  55: "Olayout",
  56: "Olayout",
  57: "Jlayout",
  58: "Olayout",
  59: "Hlayout",
  60: "Olayout",
  61: "Flayout",
  62: "Blayout",
  63: "Blayout",
  64: "Blayout",
  65: "Blayout",
  66: "Blayout",
  67: "Flayout",
};

const popUpData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-2.png",
      buttonName: "Abrir",
    },
  ],
  17: "",
  18: " ",
  19: "",
  20: "",
  21: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG21POP-1.png",
      buttonName: "Abrir",
    },
  ],
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-2.png",
      buttonName: "Abrir",
    },
  ],
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1.png",
      buttonName: "Abrir",
    },
  ],
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP-1.png",
      buttonName: "Abrir",
    },
  ],
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-1.png",
      buttonName: " Escucha activa I: Atención y concentración",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-2.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-3.png",
      buttonName: "Comunicación empática I: Observación de emociones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-4.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-5.png",
      buttonName: " Comunicación asertiva",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-6.png",
      buttonName: " Tono de voz adecuado",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-7.png",
      buttonName: "< Imparcialidad del facilitador/a>",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-8.png",
      buttonName: "Resolución de conflictos",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-9.png",
      buttonName: "Conocimiento del enfoque restaurativo",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-10.png",
      buttonName: "Conocimiento de la comunidad educativa",
    },
  ],
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const popUp_xs_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1_XS.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG4POP-2_XS.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-1_XS.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-2_XS.png",
      buttonName: "Abrir",
    },
  ],
  17: "",
  18: " ",
  19: "",
  20: "",
  21: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG21POP-1_XS.png",
      buttonName: "Abrir",
    },
    // {
    // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    // typeofContent: "image",
    // contentModal:
    // "PAG22POP-2_XS.png",
    // buttonName: "Abrir",
    //},
  ],
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "", //[
  //{
  // title: " ",
  // typeofContent: "image",
  // contentModal: "PAG32POP-1_XS.png",
  // buttonName: "Abrir",
  //},
  //{
  // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
  //typeofContent: "image",
  //contentModal:
  //"PAG32POP-2_XS.png",
  //buttonName: "Abrir",
  //},
  //],
  33: "",
  34: "",
  35: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-1_XS.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG35POP-2_XS.png",
      buttonName: "Abrir",
    },
  ],
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1_XS.png",
      buttonName: "Abrir",
    },
    // {
    // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //  typeofContent: "image",
    //contentModal:
    //"PAG38POP-2_XS.png",
    //buttonName: "Abrir",
    //    },
  ],
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP-1_XS.png",
      buttonName: "Abrir",
    },
    //   {
    //    title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //      typeofContent: "image",
    //      contentModal:
    //      "PAG48POP-2_XS.png",
    //      buttonName: "Abrir",
    //    },
  ],
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-1_XS.png",
      buttonName: " Escucha activa I: Atención y concentración",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-2_XS.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-3_XS.png",
      buttonName: "Comunicación empática I: Observación de emociones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-4_XS.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-5_XS.png",
      buttonName: " Comunicación asertiva",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-6_XS.png",
      buttonName: " Tono de voz adecuado",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-7_XS.png",
      buttonName: "< Imparcialidad del facilitador/a>",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-8_XS.png",
      buttonName: "Resolución de conflictos",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-9_XS.png",
      buttonName: "Conocimiento del enfoque restaurativo",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-10_XS.png",
      buttonName: "Conocimiento de la comunidad educativa",
    },
  ],
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const popUp_sm_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG4POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  17: "",
  18: " ",
  19: "",
  20: "",
  21: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG21POP-1_SM.png",
      buttonName: "Abrir",
    },
    // {
    // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    // typeofContent: "image",
    // contentModal:
    // "PAG22POP-2_SM.png",
    // buttonName: "Abrir",
    //},
  ],
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "", //[
  //{
  // title: " ",
  // typeofContent: "image",
  // contentModal: "PAG32POP-1_SM.png",
  // buttonName: "Abrir",
  //},
  //{
  // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
  //typeofContent: "image",
  //contentModal:
  //"PAG32POP-2_SM.png",
  //buttonName: "Abrir",
  //},
  //],
  33: "",
  34: "",
  35: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG35POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1_SM.png",
      buttonName: "Abrir",
    },
    // {
    // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //  typeofContent: "image",
    //contentModal:
    //"PAG38POP-2_SM.png",
    //buttonName: "Abrir",
    //    },
  ],
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP-1_SM.png",
      buttonName: "Abrir",
    },
    //   {
    //    title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //      typeofContent: "image",
    //      contentModal:
    //      "PAG48POP-2_SM.png",
    //      buttonName: "Abrir",
    //    },
  ],
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-1_SM.png",
      buttonName: " Escucha activa I: Atención y concentración",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-2_SM.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-3_SM.png",
      buttonName: "Comunicación empática I: Observación de emociones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-4_SM.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-5_SM.png",
      buttonName: " Comunicación asertiva",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-6_SM.png",
      buttonName: " Tono de voz adecuado",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-7_SM.png",
      buttonName: "< Imparcialidad del facilitador/a>",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-8_SM.png",
      buttonName: "Resolución de conflictos",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-9_SM.png",
      buttonName: "Conocimiento del enfoque restaurativo",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-10_SM.png",
      buttonName: "Conocimiento de la comunidad educativa",
    },
  ],
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const popUp_md_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG4POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  17: "",
  18: " ",
  19: "",
  20: "",
  21: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG21POP-1_MD.png",
      buttonName: "Abrir",
    }, // { // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", // typeofContent: "image", // contentModal: // "PAG22POP-2_MD.png", // buttonName: "Abrir", //},
  ],
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "", //[ //{ // title: " ", // typeofContent: "image", // contentModal: "PAG32POP-1_MD.png", // buttonName: "Abrir", //}, //{ // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", //typeofContent: "image", //contentModal: //"PAG32POP-2_MD.png", //buttonName: "Abrir", //}, //],
  33: "",
  34: "",
  35: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG35POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1_MD.png",
      buttonName: "Abrir",
    }, // { // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", //  typeofContent: "image",
    //contentModal:
    //"PAG38POP-2_MD.png",
    //buttonName: "Abrir",
    //    },
  ],
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP-1_MD.png",
      buttonName: "Abrir",
    },
    //   { //    title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //      typeofContent: "image",
    //      contentModal:
    //      "PAG48POP-2_MD.png",
    //      buttonName: "Abrir",
    //    },
  ],
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-1_MD.png",
      buttonName: " Escucha activa I: Atención y concentración",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-2_MD.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-3_MD.png",
      buttonName: "Comunicación empática I: Observación de emociones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-4_MD.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-5_MD.png",
      buttonName: " Comunicación asertiva",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-6_MD.png",
      buttonName: " Tono de voz adecuado",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-7_MD.png",
      buttonName: "< Imparcialidad del facilitador/a>",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-8_MD.png",
      buttonName: "Resolución de conflictos",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-9_MD.png",
      buttonName: "Conocimiento del enfoque restaurativo",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-10_MD.png",
      buttonName: "Conocimiento de la comunidad educativa",
    },
  ],
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const images_xs_Data = {
  0: "caratula_XS.png",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_XS.png",
  5: "PAG5-1_XS.png",
  6: ["PAG6-1_XS.png", "PAG6-2_XS.png"],
  7: "PAG7-1_XS.png",
  8: ["PAG8-1_XS.png", "PAG8-2_XS.png"],
  9: "PAG9-1_XS.png",
  10: "PAG10-1_XS.png",
  11: ["PAG11-1_XS.png", "PAG11-2_XS.png"],
  12: "PAG12-1_XS.png",
  13: [
    "PAG13-1_XS.png",
    "PAG13-2_XS.png",
    "PAG13-3_XS.png",
    "PAG13-4_XS.png",
    "PAG13-5_XS.png",
  ],
  14: ["PAG14-1_XS.png", "PAG14-2_XS.png"],
  15: [
    "PAG15-1_XS.png",
    "PAG15-2_XS.png",
    "PAG15-3_XS.png",
    "PAG15-4_XS.png",
    "PAG15-5_XS.png",
  ],
  16: "PAG16-1_XS.png",
  17: "PAG17-1_XS.png",
  18: "PAG18-1_XS.png",
  19: [
    "PAG19-1_XS.png",
    "PAG19-2_XS.png",
    "PAG19-3_XS.png",
    "PAG19-4_XS.png",
    "PAG19-5_XS.png",
  ],
  20: "PAG20-1_XS.png",
  21: "PAG21-1_XS.png",
  22: ["PAG22-1_XS.png", "PAG22-2_XS.png"],
  23: "PAG23-1_XS.png",
  24: ["PAG24-1_XS.png", "PAG24-2_XS.png"],
  25: [
    "PAG25-1_XS.png",
    "PAG25-2_XS.png",
    "PAG25-3_XS.png",
    "PAG25-4_XS.png",
    "PAG25-5_XS.png",
  ],
  26: "PAG26-1_XS.png",
  27: "PAG27-1_XS.png",
  28: ["PAG28-1_XS.png", "PAG28-2_XS.png"],
  29: ["PAG29-1_XS.png", "PAG29-2_XS.png"],
  30: "PAG30-1_XS.png",
  31: "PAG31-1_XS.png",
  32: "PAG32-1_XS.png",
  33: [
    "PAG33-1_XS.png",
    "PAG33-2_XS.png",
    "PAG33-3_XS.png",
    "PAG33-4_XS.png",
    "PAG33-5_XS.png",
  ],
  34: "PAG34-1_XS.png",
  35: "PAG35-1_XS.png",
  36: [
    "PAG36-1_XS.png",
    "PAG36-2_XS.png",
    "PAG36-3_XS.png",
    "PAG36-4_XS.png",
    "PAG36-5_XS.png",
  ],
  37: "PAG37-1_XS.png",
  38: "PAG38-1_XS.png",
  39: [
    "PAG39-1_XS.png",
    "PAG39-2_XS.png",
    "PAG39-3_XS.png",
    "PAG39-4_XS.png",
    "PAG39-5_XS.png",
  ],
  40: "PAG40-1_XS.png",
  41: ["PAG41-1_XS.png", "PAG41-2_XS.png"],
  42: [
    "PAG42-1_XS.png",
    "PAG42-2_XS.png",
    "PAG42-3_XS.png",
    "PAG42-4_XS.png",
    "PAG42-5_XS.png",
  ],
  43: ["PAG43-1_XS.png", "PAG43-2_XS.png"],
  44: "PAG44-1_XS.png",
  45: ["PAG45-1_XS.png", "PAG45-2_XS.png"],
  46: "PAG46-1_XS.png",
  47: [
    "PAG47-1_XS.png",
    "PAG47-2_XS.png",
    "PAG47-3_XS.png",
    "PAG47-4_XS.png",
    "PAG47-5_XS.png",
  ],
  48: "PAG48-1_XS.png",
  49: "PAG49-1_XS.png",
  50: [
    "PAG50-1_XS.png",
    "PAG50-2_XS.png",
    "PAG50-3_XS.png",
    "PAG50-4_XS.png",
    "PAG50-5_XS.png",
  ],
  51: "PAG51-1_XS.png",
  52: [
    "PAG52-1_XS.png",
    "PAG52-2_XS.png",
    "PAG52-3_XS.png",
    "PAG52-4_XS.png",
    "PAG52-5_XS.png",
  ],
  53: "PAG53-1_XS.png",
  54: "PAG54-1_XS.png",
  55: "PAG55-1_XS.png",
  56: "PAG56-1_XS.png",
  57: [
    "PAG57-1_XS.png",
    "PAG57-2_XS.png",
    "PAG57-3_XS.png",
    "PAG57-4_XS.png",
    "PAG57-5_XS.png",
  ],
  58: "PAG58-1_XS.png",
  59: "",
  60: "PAG60-1_XS.png",
  61: ["PAG61-1_XS.png", "PAG61-2_XS.png"],
  62: " ",
  63: " ",
  64: " ",
  65: " ",
  66: " ",
  67: ["PAG67-1_XS.png", "PAG67-2_XS.png"],
};
const images_sm_Data = {
  0: "caratula_SM.png",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_SM.png",
  5: "PAG5-1_SM.png",
  6: ["PAG6-1_SM.png", "PAG6-2_SM.png"],
  7: "PAG7-1_SM.png",
  8: ["PAG8-1_SM.png", "PAG8-2_SM.png"],
  9: "PAG9-1_SM.png",
  10: "PAG10-1_SM.png",
  11: ["PAG11-1_SM.png", "PAG11-2_SM.png"],
  12: "PAG12-1_SM.png",
  13: [
    "PAG13-1_SM.png",
    "PAG13-2_SM.png",
    "PAG13-3_SM.png",
    "PAG13-4_SM.png",
    "PAG13-5_SM.png",
  ],
  14: ["PAG14-1_SM.png", "PAG14-2_SM.png"],
  15: [
    "PAG15-1_SM.png",
    "PAG15-2_SM.png",
    "PAG15-3_SM.png",
    "PAG15-4_SM.png",
    "PAG15-5_SM.png",
  ],
  16: "PAG16-1_SM.png",
  17: "PAG17-1_SM.png",
  18: "PAG18-1_SM.png",
  19: [
    "PAG19-1_SM.png",
    "PAG19-2_SM.png",
    "PAG19-3_SM.png",
    "PAG19-4_SM.png",
    "PAG19-5_SM.png",
  ],
  20: "PAG20-1_SM.png",
  21: "PAG21-1_SM.png",
  22: ["PAG22-1_SM.png", "PAG22-2_SM.png"],
  23: "PAG23-1_SM.png",
  24: ["PAG24-1_SM.png", "PAG24-2_SM.png"],
  25: [
    "PAG25-1_SM.png",
    "PAG25-2_SM.png",
    "PAG25-3_SM.png",
    "PAG25-4_SM.png",
    "PAG25-5_SM.png",
  ],
  26: "PAG26-1_SM.png",
  27: "PAG27-1_SM.png",
  28: ["PAG28-1_SM.png", "PAG28-2_SM.png"],
  29: ["PAG29-1_SM.png", "PAG29-2_SM.png"],
  30: "PAG30-1_SM.png",
  31: "PAG31-1_SM.png",
  32: "PAG32-1_SM.png",
  33: [
    "PAG33-1_SM.png",
    "PAG33-2_SM.png",
    "PAG33-3_SM.png",
    "PAG33-4_SM.png",
    "PAG33-5_SM.png",
  ],
  34: "PAG34-1_SM.png",
  35: "PAG35-1_SM.png",
  36: [
    "PAG36-1_SM.png",
    "PAG36-2_SM.png",
    "PAG36-3_SM.png",
    "PAG36-4_SM.png",
    "PAG36-5_SM.png",
  ],
  37: "PAG37-1_SM.png",
  38: "PAG38-1_SM.png",
  39: [
    "PAG39-1_SM.png",
    "PAG39-2_SM.png",
    "PAG39-3_SM.png",
    "PAG39-4_SM.png",
    "PAG39-5_SM.png",
  ],
  40: "PAG40-1_SM.png",
  41: ["PAG41-1_SM.png", "PAG41-2_SM.png"],
  42: [
    "PAG42-1_SM.png",
    "PAG42-2_SM.png",
    "PAG42-3_SM.png",
    "PAG42-4_SM.png",
    "PAG42-5_SM.png",
  ],
  43: ["PAG43-1_SM.png", "PAG43-2_SM.png"],
  44: "PAG44-1_SM.png",
  45: ["PAG45-1_SM.png", "PAG45-2_SM.png"],
  46: "PAG46-1_SM.png",
  47: [
    "PAG47-1_SM.png",
    "PAG47-2_SM.png",
    "PAG47-3_SM.png",
    "PAG47-4_SM.png",
    "PAG47-5_SM.png",
  ],
  48: "PAG48-1_SM.png",
  49: "PAG49-1_SM.png",
  50: [
    "PAG50-1_SM.png",
    "PAG50-2_SM.png",
    "PAG50-3_SM.png",
    "PAG50-4_SM.png",
    "PAG50-5_SM.png",
  ],
  51: "PAG51-1_SM.png",
  52: [
    "PAG52-1_SM.png",
    "PAG52-2_SM.png",
    "PAG52-3_SM.png",
    "PAG52-4_SM.png",
    "PAG52-5_SM.png",
  ],
  53: "PAG53-1_SM.png",
  54: "PAG54-1_SM.png",
  55: "PAG55-1_SM.png",
  56: "PAG56-1_SM.png",
  57: [
    "PAG57-1_SM.png",
    "PAG57-2_SM.png",
    "PAG57-3_SM.png",
    "PAG57-4_SM.png",
    "PAG57-5_SM.png",
  ],
  58: "PAG58-1_SM.png",
  59: "",
  60: "PAG60-1_SM.png",
  61: ["PAG61-1_SM.png", "PAG61-2_SM.png"],
  62: " ",
  63: " ",
  64: " ",
  65: " ",
  66: " ",
  67: ["PAG67-1_SM.png", "PAG67-2_SM.png"],
};
const images_md_Data = {
  0: "caratula_MD.png",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_MD.png",
  5: "PAG5-1_MD.png",
  6: ["PAG6-1_MD.png", "PAG6-2_MD.png"],
  7: "PAG7-1_MD.png",
  8: ["PAG8-1_MD.png", "PAG8-2_MD.png"],
  9: "PAG9-1_MD.png",
  10: "PAG10-1_MD.png",
  11: ["PAG11-1_MD.png", "PAG11-2_MD.png"],
  12: "PAG12-1_MD.png",
  13: [
    "PAG13-1_MD.png",
    "PAG13-2_MD.png",
    "PAG13-3_MD.png",
    "PAG13-4_MD.png",
    "PAG13-5_MD.png",
  ],
  14: ["PAG14-1_MD.png", "PAG14-2_MD.png"],
  15: [
    "PAG15-1_MD.png",
    "PAG15-2_MD.png",
    "PAG15-3_MD.png",
    "PAG15-4_MD.png",
    "PAG15-5_MD.png",
  ],
  16: "PAG16-1_MD.png",
  17: "PAG17-1_MD.png",
  18: "PAG18-1_MD.png",
  19: [
    "PAG19-1_MD.png",
    "PAG19-2_MD.png",
    "PAG19-3_MD.png",
    "PAG19-4_MD.png",
    "PAG19-5_MD.png",
  ],
  20: "PAG20-1_MD.png",
  21: "PAG21-1_MD.png",
  22: ["PAG22-1_MD.png", "PAG22-2_MD.png"],
  23: "PAG23-1_MD.png",
  24: ["PAG24-1_MD.png", "PAG24-2_MD.png"],
  25: [
    "PAG25-1_MD.png",
    "PAG25-2_MD.png",
    "PAG25-3_MD.png",
    "PAG25-4_MD.png",
    "PAG25-5_MD.png",
  ],
  26: "PAG26-1_MD.png",
  27: "PAG27-1_MD.png",
  28: ["PAG28-1_MD.png", "PAG28-2_MD.png"],
  29: ["PAG29-1_MD.png", "PAG29-2_MD.png"],
  30: "PAG30-1_MD.png",
  31: "PAG31-1_MD.png",
  32: "PAG32-1_MD.png",
  33: [
    "PAG33-1_MD.png",
    "PAG33-2_MD.png",
    "PAG33-3_MD.png",
    "PAG33-4_MD.png",
    "PAG33-5_MD.png",
  ],
  34: "PAG34-1_MD.png",
  35: "PAG35-1_MD.png",
  36: [
    "PAG36-1_MD.png",
    "PAG36-2_MD.png",
    "PAG36-3_MD.png",
    "PAG36-4_MD.png",
    "PAG36-5_MD.png",
  ],
  37: "PAG37-1_MD.png",
  38: "PAG38-1_MD.png",
  39: [
    "PAG39-1_MD.png",
    "PAG39-2_MD.png",
    "PAG39-3_MD.png",
    "PAG39-4_MD.png",
    "PAG39-5_MD.png",
  ],
  40: "PAG40-1_MD.png",
  41: ["PAG41-1_MD.png", "PAG41-2_MD.png"],
  42: [
    "PAG42-1_MD.png",
    "PAG42-2_MD.png",
    "PAG42-3_MD.png",
    "PAG42-4_MD.png",
    "PAG42-5_MD.png",
  ],
  43: ["PAG43-1_MD.png", "PAG43-2_MD.png"],
  44: "PAG44-1_MD.png",
  45: ["PAG45-1_MD.png", "PAG45-2_MD.png"],
  46: "PAG46-1_MD.png",
  47: [
    "PAG47-1_MD.png",
    "PAG47-2_MD.png",
    "PAG47-3_MD.png",
    "PAG47-4_MD.png",
    "PAG47-5_MD.png",
  ],
  48: "PAG48-1_MD.png",
  49: "PAG49-1_MD.png",
  50: [
    "PAG50-1_MD.png",
    "PAG50-2_MD.png",
    "PAG50-3_MD.png",
    "PAG50-4_MD.png",
    "PAG50-5_MD.png",
  ],
  51: "PAG51-1_MD.png",
  52: [
    "PAG52-1_MD.png",
    "PAG52-2_MD.png",
    "PAG52-3_MD.png",
    "PAG52-4_MD.png",
    "PAG52-5_MD.png",
  ],
  53: "PAG53-1_MD.png",
  54: "PAG54-1_MD.png",
  55: "PAG55-1_MD.png",
  56: "PAG56-1_MD.png",
  57: [
    "PAG57-1_MD.png",
    "PAG57-2_MD.png",
    "PAG57-3_MD.png",
    "PAG57-4_MD.png",
    "PAG57-5_MD.png",
  ],
  58: "PAG58-1_MD.png",
  59: "",
  60: "PAG60-1_MD.png",
  61: ["PAG61-1_MD.png", "PAG61-2_MD.png"],
  62: " ",
  63: " ",
  64: " ",
  65: " ",
  66: " ",
  67: ["PAG67-1_MD.png", "PAG67-2_MD.png"],
};
const imagesData = {
  0: "caratula.png",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png"],
  9: "PAG9-1.png",
  10: "PAG10-1.png",
  11: ["PAG11-1.png", "PAG11-2.png"],
  12: "PAG12-1.png",
  13: [
    "PAG13-1.png",
    "PAG13-2.png",
    "PAG13-3.png",
    "PAG13-4.png",
    "PAG13-5.png",
  ],
  14: ["PAG14-1.png", "PAG14-2.png"],
  15: [
    "PAG15-1.png",
    "PAG15-2.png",
    "PAG15-3.png",
    "PAG15-4.png",
    "PAG15-5.png",
  ],
  16: "PAG16-1.png",
  17: "PAG17-1.png",
  18: "PAG18-1.png",
  19: [
    "PAG19-1.png",
    "PAG19-2.png",
    "PAG19-3.png",
    "PAG19-4.png",
    "PAG19-5.png",
  ],
  20: "PAG20-1.png",
  21: "PAG21-1.png",
  22: ["PAG22-1.png", "PAG22-2.png"],
  23: "PAG23-1.png",
  24: ["PAG24-1.png", "PAG24-2.png"],
  25: [
    "PAG25-1.png",
    "PAG25-2.png",
    "PAG25-3.png",
    "PAG25-4.png",
    "PAG25-5.png",
  ],
  26: "PAG26-1.png",
  27: "PAG27-1.png",
  28: ["PAG28-1.png", "PAG28-2.png"],
  29: ["PAG29-1.png", "PAG29-2.png"],
  30: "PAG30-1.png",
  31: "PAG31-1.png",
  32: "PAG32-1.png",
  33: [
    "PAG33-1.png",
    "PAG33-2.png",
    "PAG33-3.png",
    "PAG33-4.png",
    "PAG33-5.png",
  ],
  34: "PAG34-1.png",
  35: "PAG35-1.png",
  36: [
    "PAG36-1.png",
    "PAG36-2.png",
    "PAG36-3.png",
    "PAG36-4.png",
    "PAG36-5.png",
  ],
  37: "PAG37-1.png",
  38: "PAG38-1.png",
  39: [
    "PAG39-1.png",
    "PAG39-2.png",
    "PAG39-3.png",
    "PAG39-4.png",
    "PAG39-5.png",
  ],
  40: "PAG40-1.png",
  41: ["PAG41-1.png", "PAG41-2.png"],
  42: [
    "PAG42-1.png",
    "PAG42-2.png",
    "PAG42-3.png",
    "PAG42-4.png",
    "PAG42-5.png",
  ],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "PAG44-1.png",
  45: ["PAG45-1.png", "PAG45-2.png"],
  46: "PAG46-1.png",
  47: [
    "PAG47-1.png",
    "PAG47-2.png",
    "PAG47-3.png",
    "PAG47-4.png",
    "PAG47-5.png",
  ],
  48: "PAG48-1.png",
  49: "PAG49-1.png",
  50: [
    "PAG50-1.png",
    "PAG50-2.png",
    "PAG50-3.png",
    "PAG50-4.png",
    "PAG50-5.png",
  ],
  51: "PAG51-1.png",
  52: [
    "PAG52-1.png",
    "PAG52-2.png",
    "PAG52-3.png",
    "PAG52-4.png",
    "PAG52-5.png",
  ],
  53: "PAG53-1.png",
  54: "PAG54-1.png",
  55: "PAG55-1.png",
  56: "PAG56-1.png",
  57: ["PAG57-1.png", "PAG57-2.png", "PAG57-3.png", "PAG57-4.png"],
  58: "PAG58-1.png",
  59: "",
  60: "PAG60-1.png",
  61: ["PAG61-1.png", "PAG61-2.png"],
  62: " ",
  63: " ",
  64: " ",
  65: " ",
  66: " ",
  67: ["PAG67-1.png", "PAG67-2.png"],
};

const buttonsNameData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [
    "Actividad de inicio",
    "Escucha activa",
    "Declaraciones afectivas",
    "Construcción de las declaraciones afectivas",
    "Actividad sugerida",
  ],
  6: "",
  7: "",
  8: "",
  9: ["Mejora las relaciones", "Entorno Estimulante", "Dialogo y resolución"],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: [
    "Actividad de inicio",
    "Círculos restaurativos escolares",
    "Tipos de círculos restaurativos escolares",
    "Proceso para generar círculos restaurativos escolares",
    "Actividad sugerida",
  ],

  24: "",
  25: "",
  26: "",
  // 27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: [
    "Actividad de inicio",
    "Concepto de reunión restaurativa",
    "Desarrollo de la reunión",
    "Rol del facilitador de las reuniones restaurativas",
    "Actividad sugerida",
  ],
  45: "",
  46: "",
  47: "",
  48: "",
  49: " ",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: "",
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};

const buttonsPageNumberData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [6, 7, 13, 18, 22],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: [24, 25, 33, 36, 43],
  24: "",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: [45, 46, 53, 58, 61],
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: "",
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const linksData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "https://docs.google.com/document/d/1fQikdmac4DeobPadCd9b1f43zw285g4a/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  7: "",
  8: "https://youtu.be/L8qIdDBm7rU?si=DEvo5AEXrw3pJb5R",
  9: "",
  10: "",
  11: "https://docs.google.com/document/d/1lHI1SD0dl6HE6c7LY4LDVTM8LDUq2W4t/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  12: "",
  13: "",
  14: "https://gestaltsalut.com/comunicacion-noviolenta-rosenberg/",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "https://docs.google.com/document/d/1h0XUFlfwtEDEqIutDquK_NshN9bM8_cz/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  23: "",
  24: "https://docs.google.com/document/d/1sWQC9FD53sJo8kevxdFx-C0j1HCL7_6r/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "https://docs.google.com/document/d/1QdIIRUHlm_uCq_ufGPugMSVg_mCqil4w/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  29: "https://youtu.be/e2criL_Dsio?si=KiYmm-Zz79wXlJQb",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "https://www.youtube.com/watch?v=JRg0XRfNaBc",
  42: "",
  43: "https://docs.google.com/document/d/1FkHMZcivZ3sXvdrHos3N32FuveK-g8wO/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  44: "",
  45: "https://docs.google.com/document/d/1gyqEjxEciqgX-n9vtNjfx1HdAWxq2mZI/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: "",
  60: "",
  61: "https://docs.google.com/document/d/1JzSvHVP4mkod5vxiu9VRtBe-y1yWdibT/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "https://docs.google.com/document/d/1NozBAL8WQOsrrS8smHjVHB-YYjuzrPne/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
};
