const popUpData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG4POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG16POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  17: "",
  18: " ",
  19: "",
  20: "",
  21: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG21POP-1_MD.png",
      buttonName: "Abrir",
    }, // { // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", // typeofContent: "image", // contentModal: // "PAG22POP-2_MD.png", // buttonName: "Abrir", //},
  ],
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "", //[ //{ // title: " ", // typeofContent: "image", // contentModal: "PAG32POP-1_MD.png", // buttonName: "Abrir", //}, //{ // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", //typeofContent: "image", //contentModal: //"PAG32POP-2_MD.png", //buttonName: "Abrir", //}, //],
  33: "",
  34: "",
  35: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG35POP-1_MD.png",
      buttonName: "Abrir",
    },
    {
      title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
      typeofContent: "image",
      contentModal: "PAG35POP-2_MD.png",
      buttonName: "Abrir",
    },
  ],
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1_MD.png",
      buttonName: "Abrir",
    }, // { // title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS", //  typeofContent: "image",
    //contentModal:
    //"PAG38POP-2_MD.png",
    //buttonName: "Abrir",
    //    },
  ],
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP-1_MD.png",
      buttonName: "Abrir",
    },
    //   { //    title: "CAJA DE HERRAMIENTAS PARA LAS PRÁCTICAS RESTAURATIVAS",
    //      typeofContent: "image",
    //      contentModal:
    //      "PAG48POP-2_MD.png",
    //      buttonName: "Abrir",
    //    },
  ],
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
  59: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-1_MD.png",
      buttonName: " Escucha activa I: Atención y concentración",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-2_MD.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-3_MD.png",
      buttonName: "Comunicación empática I: Observación de emociones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-4_MD.png",
      buttonName: "Comunicación empática II: Reflejar y acompañar",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-5_MD.png",
      buttonName: " Comunicación asertiva",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-6_MD.png",
      buttonName: " Tono de voz adecuado",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-7_MD.png",
      buttonName: "< Imparcialidad del facilitador/a>",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-8_MD.png",
      buttonName: "Resolución de conflictos",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-9_MD.png",
      buttonName: "Conocimiento del enfoque restaurativo",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG59POP-10_MD.png",
      buttonName: "Conocimiento de la comunidad educativa",
    },
  ],
  60: "",
  61: "",
  62: "",
  63: "",
  64: "",
  65: "",
  66: "",
  67: "",
};
const imagesData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_MD.png",
  5: "PAG5-1_MD.png",
  6: ["PAG6-1_MD.png", "PAG6-2_MD.png"],
  7: "PAG7-1_MD.png",
  8: ["PAG8-1_MD.png", "PAG8-2_MD.png"],
  9: "PAG9-1_MD.png",
  10: "PAG10-1_MD.png",
  11: ["PAG11-1_MD.png", "PAG11-2_MD.png"],
  12: "PAG12-1_MD.png",
  13: [
    "PAG13-1_MD.png",
    "PAG13-2_MD.png",
    "PAG13-3_MD.png",
    "PAG13-4_MD.png",
    "PAG13-5_MD.png",
  ],
  14: ["PAG14-1_MD.png", "PAG14-2_MD.png"],
  15: [
    "PAG15-1_MD.png",
    "PAG15-2_MD.png",
    "PAG15-3_MD.png",
    "PAG15-4_MD.png",
    "PAG15-5_MD.png",
  ],
  16: "PAG16-1_MD.png",
  17: "PAG17-1_MD.png",
  18: "PAG18-1_MD.png",
  19: [
    "PAG19-1_MD.png",
    "PAG19-2_MD.png",
    "PAG19-3_MD.png",
    "PAG19-4_MD.png",
    "PAG19-5_MD.png",
  ],
  20: "PAG20-1_MD.png",
  21: "PAG21-1_MD.png",
  22: ["PAG22-1_MD.png", "PAG22-2_MD.png"],
  23: "PAG23-1_MD.png",
  24: ["PAG24-1_MD.png", "PAG24-2_MD.png"],
  25: [
    "PAG25-1_MD.png",
    "PAG25-2_MD.png",
    "PAG25-3_MD.png",
    "PAG25-4_MD.png",
    "PAG25-5_MD.png",
  ],
  26: "PAG26-1_MD.png",
  27: "PAG27-1_MD.png",
  28: ["PAG28-1_MD.png", "PAG28-2_MD.png"],
  29: ["PAG29-1_MD.png", "PAG29-2_MD.png"],
  30: "PAG30-1_MD.png",
  31: "PAG31-1_MD.png",
  32: "PAG32-1_MD.png",
  33: [
    "PAG33-1_MD.png",
    "PAG33-2_MD.png",
    "PAG33-3_MD.png",
    "PAG33-4_MD.png",
    "PAG33-5_MD.png",
  ],
  34: "PAG34-1_MD.png",
  35: "PAG35-1_MD.png",
  36: [
    "PAG36-1_MD.png",
    "PAG36-2_MD.png",
    "PAG36-3_MD.png",
    "PAG36-4_MD.png",
    "PAG36-5_MD.png",
  ],
  37: "PAG37-1_MD.png",
  38: "PAG38-1_MD.png",
  39: [
    "PAG39-1_MD.png",
    "PAG39-2_MD.png",
    "PAG39-3_MD.png",
    "PAG39-4_MD.png",
    "PAG39-5_MD.png",
  ],
  40: "PAG40-1_MD.png",
  41: ["PAG41-1_MD.png", "PAG41-2_MD.png"],
  42: [
    "PAG42-1_MD.png",
    "PAG42-2_MD.png",
    "PAG42-3_MD.png",
    "PAG42-4_MD.png",
    "PAG42-5_MD.png",
  ],
  43: ["PAG43-1_MD.png", "PAG43-2_MD.png"],
  44: "PAG44-1_MD.png",
  45: ["PAG45-1_MD.png", "PAG45-2_MD.png"],
  46: "PAG46-1_MD.png",
  47: [
    "PAG47-1_MD.png",
    "PAG47-2_MD.png",
    "PAG47-3_MD.png",
    "PAG47-4_MD.png",
    "PAG47-5_MD.png",
  ],
  48: "PAG48-1_MD.png",
  49: "PAG49-1_MD.png",
  50: [
    "PAG50-1_MD.png",
    "PAG50-2_MD.png",
    "PAG50-3_MD.png",
    "PAG50-4_MD.png",
    "PAG50-5_MD.png",
  ],
  51: "PAG51-1_MD.png",
  52: [
    "PAG52-1_MD.png",
    "PAG52-2_MD.png",
    "PAG52-3_MD.png",
    "PAG52-4_MD.png",
    "PAG52-5_MD.png",
  ],
  53: "PAG53-1_MD.png",
  54: "PAG54-1_MD.png",
  55: "PAG55-1_MD.png",
  56: "PAG56-1_MD.png",
  57: [
    "PAG57-1_MD.png",
    "PAG57-2_MD.png",
    "PAG57-3_MD.png",
    "PAG57-4_MD.png",
    "PAG57-5_MD.png",
  ],
  58: "PAG58-1_MD.png",
  59: "",
  60: "PAG60-1_MD.png",
  61: ["PAG61-1_MD.png", "PAG61-2_MD.png"],
  62: " ",
  63: " ",
  64: " ",
  65: " ",
  66: " ",
  67: ["PAG67-1_MD.png", "PAG67-2_MD.png"],
};
